# content  : content
#
# Date     : 2025-11-05
#
# Author   : Elena Giuliani
# email    : elenagiuliani94@outlook.it


base_dir: C:\Users\utente\Desktop\Python Advanced - 
  AlexanderRichterCourse\Elena_assignments\git_elena_assignments\5_app\app\testing_area

# PROJECT DATA
loaded_project: P_25_001__1970_ceramic_set

# FILES NAME
files_name: 1970Ceramic

# PROJECT TITLE FOR ASSETS TO SELL
marketplace_name: 1970Ceramic


#**********************
# PROJECT TYPES
project_types: ['Environment', 'Props', '3Dscans', 'Characters']

# keep these updated to add/remove software or maya tasks
env_categories: ['Architectural', 'Props', 'Lamps']
selected_tab: Architectural
#maya_tasks: ['model', 'baking', 'rig', 'pose', 'anim']
#softwares: ['maya', 'SP', 'ZB', 'SD', 'RealityScan']

# marketplace
folders_ue: ['Meshes', 'Materials', 'Textures']
folders_static_render: ['LODs', 'maya']
texture_resolutions: ['1k', '2k', '4k']

#**********************
# NAMING CONVENTION
files_naming:

  modeling:
    department: modeling
    extension: model

  baking:
    department: baking
    extension: bake

  texturing:
    department: texturing
    extension: tex

  grooming:
    department: grooming
    extension: groom

  rigging:
    department: rigging
    extension: rig

  pose:
    department: pose
    extension: pose

  animation:
    department: animation
    extension: anim

  sculpting:
    department: sculpting
    extension: sculpt

  3Dscan:
    department: scan
    extension: scan
