# content  : content
#
# Date     : 2025-11-05
#
# Author   : Elena Giuliani
# email    : elenagiuliani94@outlook.it


base_dir: F:/3D_Projects/5_PixelsAndCrafts

# PROJECT DATA
loaded_project: P_25_001__1970_ceramic_set

# PROJECT TITLE FOR ASSETS TO SELL
marketplace_project: english_cottage


#**********************
# PROJECT TYPES
project_types: ['Environment', 'Props', '3Dscans', 'Characters']

# keep these updated to add/remove software or maya tasks
env_categories: ['Architectural', 'Props', 'Lamps']
maya_tasks: ['model', 'baking', 'rig', 'pose', 'anim']
softwares: ['maya', 'SP', 'ZB', 'SD', 'RealityScan']

# marketplace
folders_ue: ['Meshes', 'Materials', 'Textures']
folders_static_render: ['LODs', 'maya']
texture_resolutions: ['1k', '2k', '4k']
selected_project: E_25_001__LAapartment_MarriageStory

