# Content  : project configuration file
#
# Date     : 2025-12-04
#
# license  : MIT
# Author   : Elena Giuliani
# email    : elenagiuliani94@outlook.it

projects_root: ''

# PROJECT DATA
loaded_project: ''

# FILES NAME
files_name: ''

# PROJECT TITLE FOR ASSETS TO SELL
marketplace_name: ''

#**********************
selected_tab: Architectural
