#****************************************************
#****************************************************
# content  : content
#
# Date     : 2025-11-05
#
# Author   : Elena Giuliani
# email    : elenagiuliani94@outlook.it
#****************************************************
#****************************************************
PixelsAndCrafts: F:/3D_Projects/5_PixelsAndCrafts
Characters: F:/3D_Projects/4_Lena_Projects/projects

selected_project: E_25_002__The_Haunting_Of_Hill_House
