#****************************************************
#****************************************************
# content  : content
#
# Date     : 2025-11-05
#
# Author   : Elena Giuliani
# email    : elenagiuliani94@outlook.it
#****************************************************
#****************************************************
# manual update
PixelsAndCrafts: F:/3D_Projects/5_PixelsAndCrafts
Characters: F:/3D_Projects/4_Lena_Projects/projects

# PROJECT TITLE
# they auto updates
selected_project: E_25_003__Sense_and_Sensibility

# PROJECT TITLE FOR ASSETS TO SELL
cgtrader_project_name: english_cottage


#**********************
# manual update:
# (overwrite the existing elements to match them in the UI)

# PROJECT TYPES
project_types: ['Environment', 'Props', '3Dscans', 'Characters']


# keep these updated to add/remove software or maya tasks
env_categories: ['Architectural', 'Props', 'Lamps']
maya_tasks: ['model', 'baking', 'rig', 'pose', 'anim']
softwares: ['maya', 'SP', 'ZB', 'SD', 'RealityScan']


# CGTRADER
sub_folders_ue: ['Meshes', 'Materials', 'Textures']
sub_folders_static_render: ['LODs', 'maya']
texture_resolutions: ['1k', '2k', '4k']

